### ISSUE TITLE
提点意见

### ISSUE THREAD

**Issue by yanyin1986** [simonzhang0428/De-Anza-College-CIS-36B#1]
https://github.com/simonzhang0428/De-Anza-College-CIS-36B/blob/60821a005ce27cc92ccd7b12c8ebcedf2ee0c934/Lab3/TextTrans.java#L25-L27

既然新建了`infile`这个File对象，是不是应该在下面有所体现比较好？
Scanner(infile) ?

**Comment by simonzhang0428** [comment]
有道理，我去看看，修改好了再上传，感谢yy

**Comment by yanyin1986** [comment]
@simonzhang0428 可以在新的分支上修改试试看

**Comment by yanyin1986** [comment]
先关闭了，等待你的Pull Request。
